#---
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: valheim
#spec:
#  persistentVolumeReclaimPolicy: Retain
#  storageClassName: gp2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: valheim
  name: valheim
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 30Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: valheim
  namespace: valheim
  name: valheim
spec:
  replicas: 1
  selector:
    matchLabels:
      app: valheim
  template:
    metadata:
      labels:
        app: valheim
    spec:
      nodeSelector:
        lifecycle: spot
      containers:
      - name: valheim
        image: mbround18/valheim:latest
        env:
        - name: PORT
          value: "2456"
        - name: NAME
          value: "its1037somewhere"
        - name: WORLD
          value: "myFirstWorld"
        - name: PASSWORD
          value: "monster"
        - name: TZ
          value: America/New_York
        - name: PUBLIC
          value: "1"
        - name: AUTO_UPDATE
          value: "1"
        - name: AUTO_UPDATE_SCHEDULE
          value: "0 1 * * *"
        - name: AUTO_BACKUP
          value: "1"
        - name: AUTO_BACKUP_SCHEDULE
          value: "*/15 * * * *"
        - name: AUTO_BACKUP_REMOVE_OLD
          value: "1"
        - name: AUTO_BACKUP_DAYS_TO_LIVE
          value: "3"
        - name: AUTO_BACKUP_ON_UPDATE
          value: "1"
        - name: AUTO_BACKUP_ON_SHUTDOWN
          value: "1"
        imagePullPolicy: Always
        ports:
        - containerPort: 2456
        - containerPort: 2457
        - containerPort: 2458
        resources:
          limits:
            cpu: 2
            memory: 4Gi
        volumeMounts:
        - name: valheim
          mountPath: /home/steam/.config/unity3d/IronGate/Valheim
          subPath: saves
        - name: valheim
          mountPath: /home/steam/valheim
          subPath: server
        - name: valheim
          mountPath: /home/steam/backups
          subPath: backups
      volumes:
      - name: valheim
        persistentVolumeClaim:
          claimName: valheim
---
apiVersion: v1
kind: Service
metadata:
  namespace: valheim
  name: valheim
spec:
  ports:
  - name: 2456
    port: 2456
    protocol: UDP
    targetPort: 2456
  - name: 2457
    port: 2457
    protocol: UDP
    targetPort: 2457
  - name: 2458
    port: 2458
    protocol: UDP
    targetPort: 2458
  selector:
    matchLabels:
      app: valheim
  type: ClusterIP
