apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata: 
  name: kubelet-stats-exporter
  namespace: monitor
  labels:
    name: kubelet-stats-exporter
    release: prometheus
spec: 
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 30s
    port: metrics
    scheme: http
    honorLabels: true
  jobLabel: jobLabel
  selector:
    matchLabels:
      name: kubelet-stats-exporter
  namespaceSelector:
    matchNames:
    - monitor
